apiVersion: apps/v1
kind: Deployment
metadata:
  name: gt-python
spec:
  replicas: {{ .Values.gtPython.replicas }}
  selector:
    matchLabels:
      app: gt-python
  template:
    metadata:
      labels:
        app: gt-python
    spec:
      containers:
        - name: gt-python
          image: {{ .Values.gtPython.image }}
          ports:
            - containerPort: 8000
