// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: proto/worker.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TicketWorker_PushTask_FullMethodName = "/worker.TicketWorker/PushTask"
)

// TicketWorkerClient is the client API for TicketWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// protoc --go_out=. --go-grpc_out=. proto/worker.proto
type TicketWorkerClient interface {
	PushTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
}

type ticketWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewTicketWorkerClient(cc grpc.ClientConnInterface) TicketWorkerClient {
	return &ticketWorkerClient{cc}
}

func (c *ticketWorkerClient) PushTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, TicketWorker_PushTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TicketWorkerServer is the server API for TicketWorker service.
// All implementations must embed UnimplementedTicketWorkerServer
// for forward compatibility.
//
// protoc --go_out=. --go-grpc_out=. proto/worker.proto
type TicketWorkerServer interface {
	PushTask(context.Context, *TaskRequest) (*TaskResponse, error)
	mustEmbedUnimplementedTicketWorkerServer()
}

// UnimplementedTicketWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTicketWorkerServer struct{}

func (UnimplementedTicketWorkerServer) PushTask(context.Context, *TaskRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushTask not implemented")
}
func (UnimplementedTicketWorkerServer) mustEmbedUnimplementedTicketWorkerServer() {}
func (UnimplementedTicketWorkerServer) testEmbeddedByValue()                      {}

// UnsafeTicketWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TicketWorkerServer will
// result in compilation errors.
type UnsafeTicketWorkerServer interface {
	mustEmbedUnimplementedTicketWorkerServer()
}

func RegisterTicketWorkerServer(s grpc.ServiceRegistrar, srv TicketWorkerServer) {
	// If the following call pancis, it indicates UnimplementedTicketWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TicketWorker_ServiceDesc, srv)
}

func _TicketWorker_PushTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketWorkerServer).PushTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketWorker_PushTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketWorkerServer).PushTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TicketWorker_ServiceDesc is the grpc.ServiceDesc for TicketWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TicketWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "worker.TicketWorker",
	HandlerType: (*TicketWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushTask",
			Handler:    _TicketWorker_PushTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/worker.proto",
}
